/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiciiRouteImport } from './routes/servicii'
import { Route as RecenziiRouteImport } from './routes/recenzii'
import { Route as ProiecteRouteImport } from './routes/proiecte'
import { Route as DespreNoiRouteImport } from './routes/despre-noi'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiRoute = ServiciiRouteImport.update({
  id: '/servicii',
  path: '/servicii',
  getParentRoute: () => rootRouteImport,
} as any)
const RecenziiRoute = RecenziiRouteImport.update({
  id: '/recenzii',
  path: '/recenzii',
  getParentRoute: () => rootRouteImport,
} as any)
const ProiecteRoute = ProiecteRouteImport.update({
  id: '/proiecte',
  path: '/proiecte',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreNoiRoute = DespreNoiRouteImport.update({
  id: '/despre-noi',
  path: '/despre-noi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/proiecte': typeof ProiecteRoute
  '/recenzii': typeof RecenziiRoute
  '/servicii': typeof ServiciiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/proiecte': typeof ProiecteRoute
  '/recenzii': typeof RecenziiRoute
  '/servicii': typeof ServiciiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/proiecte': typeof ProiecteRoute
  '/recenzii': typeof RecenziiRoute
  '/servicii': typeof ServiciiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/despre-noi'
    | '/proiecte'
    | '/recenzii'
    | '/servicii'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/despre-noi'
    | '/proiecte'
    | '/recenzii'
    | '/servicii'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/despre-noi'
    | '/proiecte'
    | '/recenzii'
    | '/servicii'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DespreNoiRoute: typeof DespreNoiRoute
  ProiecteRoute: typeof ProiecteRoute
  RecenziiRoute: typeof RecenziiRoute
  ServiciiRoute: typeof ServiciiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii': {
      id: '/servicii'
      path: '/servicii'
      fullPath: '/servicii'
      preLoaderRoute: typeof ServiciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recenzii': {
      id: '/recenzii'
      path: '/recenzii'
      fullPath: '/recenzii'
      preLoaderRoute: typeof RecenziiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proiecte': {
      id: '/proiecte'
      path: '/proiecte'
      fullPath: '/proiecte'
      preLoaderRoute: typeof ProiecteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre-noi': {
      id: '/despre-noi'
      path: '/despre-noi'
      fullPath: '/despre-noi'
      preLoaderRoute: typeof DespreNoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DespreNoiRoute: DespreNoiRoute,
  ProiecteRoute: ProiecteRoute,
  RecenziiRoute: RecenziiRoute,
  ServiciiRoute: ServiciiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
